In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from pathlib import Path

In [2]:
data_path = Path.cwd().parent/'data'/'cleaned_exp1'

In [3]:
for i in data_path.iterdir():
    print(i)

/Users/josephpruitt/Desktop/SDT_Exp/data/cleaned_exp1/all_pid_exp1A_clean.csv
/Users/josephpruitt/Desktop/SDT_Exp/data/cleaned_exp1/.DS_Store
/Users/josephpruitt/Desktop/SDT_Exp/data/cleaned_exp1/exp1A_3_cleaned.csv

In [4]:
df = pd.read_csv(data_path/'all_pid_exp1A_clean.csv')

In [5]:
#df = pd.read_csv(data_path/'exp1A_2_cleaned.csv')

In [6]:
fail_trials = df.loc[df.check_eye==0]
success_trials = df.loc[df.check_eye==1]

In [7]:
fail_trials.shape,success_trials.shape

((22, 15), (32, 15))

In [8]:
success_trials

,trialsN,Stimulus,position,signalOpac,CorrAns,trials.thisTrialN,check_eye,answerResp.keys,answerResp.corr,answerResp.rt,slider.response,participant,session,expName,degrees
0,1,signal,"[2274, 0]",1.0,1.0,0.0,1.0,2.0,0.0,0.765461,4.0,3.0,A,exp1A,40
1,2,signal,"[-557, 0]",1.0,1.0,1.0,1.0,1.0,1.0,0.413421,3.0,3.0,A,exp1A,-10
2,3,noise,"[2274, 0]",0.0,2.0,2.0,1.0,2.0,1.0,0.349067,2.0,3.0,A,exp1A,40
3,4,signal,"[-1716, 0]",1.0,1.0,3.0,1.0,1.0,1.0,0.289975,2.0,3.0,A,exp1A,-30
4,5,noise,"[1716, 0]",0.0,2.0,4.0,1.0,1.0,0.0,0.389733,1.0,3.0,A,exp1A,30
6,7,noise,"[-1716, 0]",0.0,2.0,6.0,1.0,2.0,1.0,0.468483,3.0,3.0,A,exp1A,-30
7,8,noise,"[1158, 0]",0.0,2.0,7.0,1.0,1.0,0.0,0.361541,2.0,3.0,A,exp1A,20
8,9,noise,"[-2274, 0]",0.0,2.0,8.0,1.0,1.0,0.0,0.396066,4.0,3.0,A,exp1A,-40
9,10,signal,"[-1158, 0]",1.0,1.0,9.0,1.0,2.0,0.0,0.301398,2.0,3.0,A,exp1A,-20
10,11,signal,"[-2274, 0]",1.0,1.0,10.0,1.0,1.0,1.0,0.479410,3.0,3.0,A,exp1A,-40
11,12,noise,"[0, 0]",0.0,2.0,11.0,1.0,2.0,1.0,0.576733,4.0,3.0,A,exp1A,0
12,13,signal,"[557, 0]",1.0,1.0,12.0,1.0,2.0,0.0,1.627100,1.0,3.0,A,exp1A,10
14,15,signal,"[1158, 0]",1.0,1.0,14.0,1.0,1.0,1.0,0.601458,1.0,3.0,A,exp1A,20
15,16,signal,"[0, 0]",1.0,1.0,15.0,1.0,1.0,1.0,0.909095,4.0,3.0,A,exp1A,0
17,18,signal,"[1716, 0]",1.0,1.0,17.0,1.0,1.0,1.0,0.303908,3.0,3.0,A,exp1A,30
18,19,signal,"[2274, 0]",1.0,1.0,0.0,1.0,1.0,1.0,0.971741,3.0,3.0,B,exp1A,40
19,20,signal,"[557, 0]",1.0,1.0,1.0,1.0,2.0,0.0,0.505353,4.0,3.0,B,exp1A,10
21,22,noise,"[-1716, 0]",0.0,2.0,3.0,1.0,1.0,0.0,0.574394,2.0,3.0,B,exp1A,-30
22,23,noise,"[2274, 0]",0.0,2.0,4.0,1.0,1.0,0.0,0.617538,3.0,3.0,B,exp1A,40
23,24,signal,"[-2274, 0]",1.0,1.0,5.0,1.0,1.0,1.0,2.006079,2.0,3.0,B,exp1A,-40
24,25,signal,"[1158, 0]",1.0,1.0,6.0,1.0,2.0,0.0,1.721845,1.0,3.0,B,exp1A,20
26,27,signal,"[1716, 0]",1.0,1.0,8.0,1.0,1.0,1.0,0.206119,1.0,3.0,B,exp1A,30
28,29,noise,"[-1158, 0]",0.0,2.0,10.0,1.0,1.0,0.0,0.472875,3.0,3.0,B,exp1A,-20
29,30,noise,"[-557, 0]",0.0,2.0,11.0,1.0,2.0,1.0,2.598499,2.0,3.0,B,exp1A,-10
30,31,signal,"[-1716, 0]",1.0,1.0,12.0,1.0,2.0,0.0,0.821311,4.0,3.0,B,exp1A,-30
33,34,signal,"[-557, 0]",1.0,1.0,15.0,1.0,1.0,1.0,1.115926,1.0,3.0,B,exp1A,-10
35,36,noise,"[557, 0]",0.0,2.0,17.0,1.0,2.0,1.0,0.957466,3.0,3.0,B,exp1A,10
37,38,signal,"[-1716, 0]",1.0,1.0,1.0,1.0,None,0.0,NaN,3.0,3.0,C,exp1A,-30
38,39,noise,"[0, 0]",0.0,2.0,2.0,1.0,None,0.0,NaN,2.0,3.0,C,exp1A,0
39,40,signal,"[1158, 0]",1.0,1.0,3.0,1.0,None,0.0,NaN,2.0,3.0,C,exp1A,20
40,41,noise,"[2274, 0]",0.0,2.0,4.0,1.0,1,0.0,3.691575,3.0,3.0,C,exp1A,40
41,42,noise,"[1716, 0]",0.0,2.0,5.0,1.0,0,1.0,0.375843,4.0,3.0,C,exp1A,30

In [9]:
a = df.pivot_table(index= 'participant',columns = 'check_eye',values = 'trials.thisTrialN',aggfunc='count')
a = a/540
a

check_eye         0.0       1.0
participant
3.0          0.040741  0.059259

In [22]:
acc_pos_sig = success_trials.pivot_table(index='participant',columns=['position','Stimulus'],values='answerResp.corr')

In [23]:
acc_pos = success_trials.pivot_table(index='participant',columns='position',values='answerResp.corr')

In [24]:
acc_pos

position,"[-1158, 0]","[-1716, 0]","[-2274, 0]","[-557, 0]","[0, 0]","[1158, 0]","[1716, 0]","[2274, 0]","[557, 0]"
participant,,,,,,,,,
3.0,0.0,0.4,0.666667,1.0,0.666667,0.25,0.75,0.4,0.333333

In [25]:
acc_pos = acc_pos [['[-2274, 0]','[-1716, 0]','[-1158, 0]', '[-557, 0]','[0, 0]', '[557, 0]','[1158, 0]','[1716, 0]',
                 '[2274, 0]']]

acc_pos

position,"[-2274, 0]","[-1716, 0]","[-1158, 0]","[-557, 0]","[0, 0]","[557, 0]","[1158, 0]","[1716, 0]","[2274, 0]"
participant,,,,,,,,,
3.0,0.666667,0.4,0.0,1.0,0.666667,0.333333,0.25,0.75,0.4

In [26]:
acc_pos.mean()

position
[-2274, 0]    0.666667
[-1716, 0]    0.400000
[-1158, 0]    0.000000
[-557, 0]     1.000000
[0, 0]        0.666667
[557, 0]      0.333333
[1158, 0]     0.250000
[1716, 0]     0.750000
[2274, 0]     0.400000
dtype: float64

In [27]:
acc_pos_sig = acc_pos_sig [['[-2274, 0]','[-1716, 0]','[-1158, 0]','[-557, 0]','[0, 0]', '[557, 0]','[1158, 0]','[1716, 0]',
                 '[2274, 0]']]
acc_pos_sig

position    [-2274, 0]        [-1716, 0]           [-1158, 0]         \
Stimulus         noise signal      noise    signal      noise signal
participant
3.0                0.0    1.0        0.5  0.333333        0.0    0.0

position    [-557, 0]        [0, 0]        [557, 0]        [1158, 0]  \
Stimulus        noise signal  noise signal    noise signal     noise
participant
3.0               1.0    1.0    0.5    1.0      1.0    0.0       0.0

position              [1716, 0]        [2274, 0]
Stimulus       signal     noise signal     noise signal
participant
3.0          0.333333       0.5    1.0  0.333333    0.5

In [28]:
success_trials['slider.response'] = success_trials['slider.response'].astype('float')

<ipython-input-28-74d66a053c52>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  success_trials['slider.response'] = success_trials['slider.response'].astype('float')

In [29]:
conf_pos = success_trials.pivot_table(index='participant',columns=['position'],
                                      values='slider.response')

In [30]:
conf_pos

position,"[-1158, 0]","[-1716, 0]","[-2274, 0]","[-557, 0]","[0, 0]","[1158, 0]","[1716, 0]","[2274, 0]","[557, 0]"
participant,,,,,,,,,
3.0,2.5,2.8,3.0,2.0,3.333333,1.5,2.25,3.0,2.666667